/** Public Plugin API v1 types used by this source; Runtime remains authoritative. */
export interface MgReadPluginContext { readonly dataDir: string; readonly cacheDir: string; readonly http: { fetch(input: string | URL, init?: RequestInit): Promise<Response> }; readonly resource: { proxy(request: Record<string, unknown>): string }; readonly log: { debug(event: string): void; info(event: string): void; warn(event: string): void; error(event: string): void }; readonly app: { readonly runtimeVersion: string; readonly nodeVersion: string; readonly pluginApi: number }; readonly plugin: { readonly id: string; readonly version: string }; }
export interface ContentAttribute { readonly key: string; readonly label: string; readonly value: string; }
export interface ContentSummary { readonly id: string; readonly title: string; readonly contentKind: 'novel' | 'manga'; readonly author: string | null; readonly url: string | null; readonly coverUrl: string | null; readonly description: string | null; readonly language: string | null; readonly status: 'ongoing' | 'completed' | 'hiatus' | 'unknown'; readonly access: 'free' | 'paid' | 'mixed' | 'unknown'; readonly wordCount: number | null; readonly chapterCount: number | null; readonly publishedAt: string | null; readonly updatedAt: string | null; readonly latestChapter: { readonly id: string | null; readonly title: string; readonly url: string | null; readonly updatedAt: string | null } | null; readonly categories: readonly string[]; readonly tags: readonly string[]; readonly attributes: readonly ContentAttribute[]; }
export interface ContentDetail extends ContentSummary { readonly aliases: readonly string[]; readonly catalogUrl: string | null; }
export interface SearchRequest { readonly query: string; readonly cursor: string | null; readonly pageSize: number; }
export interface DiscoverRequest { readonly target: string | null; readonly cursor: string | null; readonly collectionId: string | null; readonly pageSize: number; }
export interface ContentReferenceRequest { readonly id: string; }
export interface ChaptersRequest { readonly id: string; }
export interface ContentRequest { readonly id: string; readonly chapterId: string; }
export interface SearchSuggestionsRequest { readonly cursor: string | null; readonly pageSize: number; }
