import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import * as plugin from '../dist/index.mjs';

test('live source completes category, search, detail, catalog and content', { timeout: 60000 }, async (t) => {
  const root = await mkdtemp(join(tmpdir(), 'mgread-shudugu-live-')); t.after(() => rm(root, { recursive: true, force: true }));
  await plugin.activate({ dataDir: join(root, 'data'), cacheDir: join(root, 'cache'), http: { fetch }, resource: { proxy: () => 'http://127.0.0.1:1234/v1/source-resource/opaque' }, log: { debug() {}, info() {}, warn() {}, error() {} }, app: { runtimeVersion: 'live', nodeVersion: process.versions.node, pluginApi: 1 }, plugin: { id: 'org.mgread.shudugu', version: '0.1.5' } });
  const categories = await plugin.discover({ target: null, cursor: null, collectionId: null, pageSize: 20 });
  assert.equal(categories.kind, 'document');
  assert.ok(Buffer.byteLength(JSON.stringify(categories), 'utf8') <= 52 * 1024);
  const latest = categories.document.components.find((item) => item.id === 'shudugu-latest-section');
  assert.equal(latest?.children[0].layout, 'shelf');
  assert.ok(latest?.children[0].items.length > 0);
  const overview = categories.document.components.find((item) => item.id === 'shudugu-overview-group');
  assert.equal(overview?.type, 'group');
  assert.equal(overview.children[0].children[0].layout, 'compact');
  const completed = overview.children[1].children[0];
  assert.equal(completed.layout, 'coverGrid');
  assert.ok(completed.items.length > 0);
  assert.ok(completed.items.every((item) => item.content.coverUrl !== null));
  const category = categories.document.components.find((item) => item.id === 'shudugu-categories-section')?.children.find((item) => item.type === 'categoryCollection');
  assert.equal(category?.type, 'categoryCollection');
  assert.equal(category.layout, 'chips');
  const discovery = await plugin.discover({ target: category.categories[0].target, cursor: null, collectionId: null, pageSize: 5 });
  assert.equal(discovery.kind, 'document');
  const book = discovery.document.components[0].children[0].items[0].content;
  assert.match(book.id, /^novel:\d+$/u);
  const suggestions = await plugin.searchSuggestions({ cursor: null, pageSize: 5 });
  assert.ok(suggestions.items.length > 0);
  assert.ok(suggestions.items.every((item) => item.query.trim().length > 0));
  const chapters = await plugin.getChapters({ id: book.id });
  assert.ok(chapters.items.length > 0);
  const content = await plugin.getContent({ id: book.id, chapterId: chapters.items[0].id });
  assert.equal(content.contentKind, 'novel');
  assert.ok((content.text ?? '').length > 0);
});
