/**
 * 百度短剧原生数据源。
 *
 * 职责：直接访问百度好看短剧标签、检索、详情、分集和播放接口。
 * 生命周期：activate 只保存 Runtime 上下文；请求参数按次生成，不持久化百度会话。
 * IO：表单请求走 ctx.http；封面和视频只经 ctx.resource.proxy 输出。
 * 稳定标识：作品使用 playlet_id，章节使用百度 vid，不保存完整接口响应。
 */
import type{MgReadPluginContext}from'@mgread/source-api';type Json=Record<string,unknown>;type Context=MgReadPluginContext;type Episode={id:string;title:string};const root='https://sv.baidu.com',paths={home:'/haokan/ui-feed/playletShelfFeed?osbranch=a0',category:'/haokan/ui-feed/playletTagsFeed?osbranch=a0',common:'/appui/api?osbranch=a0',detail:'/haokan/ui-video/playlet/rec/detail?osbranch=a0',search:'/haokan/ui-interact/playlet/search/sugs?osbranch=a0',player:'/appui/api?osbranch=a0'},userAgent='Mozilla/5.0 (Linux; Android 11; M2012K10C Build/RP1A.200720.011; wv) AppleWebKit/537.36 Chrome/87.0.4280.141 Mobile Safari/537.36 haokan/7.80.0.18',headers={'User-Agent':userAgent,'Content-Type':'application/x-www-form-urlencoded; charset=utf-8','Talos-Module-Version':'1.0.71.1','Talos-Module-Name':'shortDrama'},channels=[{id:'1',title:'热门'},{id:'2',title:'新剧'},{id:'3',title:'完结'}];let context:Context|undefined;
export async function activate(next:Context){context=next;next.log.info('source_activated');}
export async function search(request:{query:string;cursor:string|null;pageSize:number}){const query=request.query.trim();if(query==='')return frozen({items:[],nextCursor:null,totalCount:0});if(request.cursor!==null)validateCursor(request.cursor,'search');const values=pickList(await post(paths.search,{search_word:query})),items=summaries(values).slice(0,clamp(request.pageSize));return frozen({items,nextCursor:null,totalCount:items.length});}
export async function searchSuggestions(_request:{cursor:string|null;pageSize:number}){return frozen({items:[],nextCursor:null});}
export async function discover(request:{target:string|null;cursor:string|null;collectionId:string|null;pageSize:number}){if(request.target===null)return frozen({kind:'document'as const,document:{components:[{type:'section',id:'baidu-playlet-channels',title:'百度短剧',subtitle:'按短剧标签浏览',icon:'video',children:[{type:'categoryCollection',id:'baidu-playlet-channel-list',layout:'chips',categories:channels.map(channel=>({id:channel.id,title:channel.title,target:`channel:${channel.id}`,count:null,url:null,icon:'video'}))}]}]}});const channel=channels.find(value=>request.target===`channel:${value.id}`);if(!channel)throw new Error('Discovery target is invalid.');const page=cursorPage(request.cursor,request.target),size=clamp(request.pageSize),values=pickList(await post(paths.category,{tag_id:channel.id,rn:9,pn:page})),contents=summaries(values).slice(0,size),collectionId=`baidu:${channel.id}`,items=contents.map(content=>frozen({content,rank:null,metric:null,recommendation:null})),continuation=values.length>=size?frozen({target:request.target,cursor:`channel:${channel.id}:${page+1}`}):null;if(request.collectionId!==null){if(request.collectionId!==collectionId)throw new Error('Discovery collection is invalid.');return frozen({kind:'append'as const,collectionId,items,continuation});}return frozen({kind:'document'as const,document:{components:[{type:'section',id:`${collectionId}:section`,title:channel.title,subtitle:null,icon:'video',children:[{type:'contentCollection',id:collectionId,layout:'coverGrid',items,continuation}]}]}});}
export async function getDetail(request:{id:string}){const id=contentId(request.id),data=await detail(id),item=summary(data.info,id);return frozen({...item,aliases:[],catalogUrl:`${root}${paths.detail}#${encodeURIComponent(id)}`,chapterCount:data.episodes.length});}
export async function getChapters(request:{id:string}){const id=contentId(request.id),data=await detail(id),items=data.episodes.map((episode,index)=>frozen({id:`playlet:${id}:${episode.id}`,title:episode.title,order:index,url:null,volumeTitle:'百度',wordCount:null,updatedAt:null,isLocked:false,attributes:[]}));return frozen({items,groups:items.length?[frozen({id:`group:${id}:main`,title:'百度',order:0,episodes:items})]:[]});}
export async function getContent(request:{id:string;chapterId:string}){const playletId=contentId(request.id),vid=chapterVid(request.chapterId,playletId),related=await post(paths.player,{'video/relate':relateBody(vid,playletId)}),entry=isObject(related)&&isObject(related['video/relate'])?related['video/relate']:related,data=isObject(entry)&&isObject(entry.data)?entry.data:entry,current=isObject(data)&&isObject(first(data.cur_video,data.video))?first(data.cur_video,data.video):data,upstream=pickUrl(current);if(!safeUrl(upstream))throw new Error('Video address is unavailable.');const mediaHeaders={Referer:`${root}/`,'User-Agent':userAgent};return frozen({chapterId:request.chapterId,contentKind:'video',title:null,updatedAt:null,text:null,pages:[],media:{url:requireContext().resource.proxy({kind:'video',url:upstream,headers:mediaHeaders}),resourceType:'video',resourcePolicy:'sessionOnly',expiresAt:null,mimeType:/\.m3u8(?:$|[?#])/iu.test(upstream)?'application/vnd.apple.mpegurl':'video/mp4',headers:mediaHeaders}});}
async function detail(playletId:string){const common=await post(paths.common,{'video/commonlist':commonListBody(playletId)}),commonVideos=pickList(isObject(common)?first(common['video/commonlist'],common):common),seed=commonVideos.map(episode).find(notNull)?.id??'',response=await post(paths.detail,{vid:seed,playlet_id:playletId}),data=isObject(response)&&isObject(response.data)?response.data:{},episodes=asArray(first(data.vid_list,data.video_list,data.episodes,data.episode_list)).map(episode).filter(notNull),info={...data,playlet_id:playletId};if(episodes.length===0&&seed!=='')episodes.push({id:seed,title:'第 1 集'});return{info,episodes};}
async function post(path:string,body:Readonly<Record<string,unknown>>){const response=await requireContext().http.fetch(`${root}${path}`,{method:'POST',headers,body:new URLSearchParams(Object.entries(body).map(([key,value])=>[key,String(value)])).toString()});if(!response.ok)throw new Error('Source request failed.');try{return JSON.parse(await response.text())as unknown;}catch{throw new Error('Source response is invalid.');}}
function commonListBody(id:string){return`enable_enter_playlet=0&seek_time=0&hotspot=0&auto_show_hot_point_panel=0&type=playlet&commonlist_id=${Date.now()}&scene=&vid=&enable_atlas=0&mark_pn=&uk=&ctime=0&from=playlet_new&id=${encodeURIComponent(id)}&rn=100&pn=1&direction=3`;}function relateBody(vid:string,id:string){return`vid=${encodeURIComponent(vid)}&type=video&from=playlet_new&playlet_id=${encodeURIComponent(id)}&tab=video`;}
function summaries(values:Json[]){const result=new Map<string,ReturnType<typeof summary>>();for(const row of values){const value=normalize(row),id=nativeId(first(value.playlet_id,value.playletId,value.id,value.nid));if(id&&text(first(value.playlet_title,value.title,value.name)))result.set(id,summary(value,id));}return[...result.values()];}function summary(value:Json,id:string){const title=text(first(value.playlet_title,value.title,value.name))||id,latest=nullable(first(value.episodes_num_text,value.progress_desc,value.episode,value.episodes));return frozen({id:`playlet:${id}`,title,contentKind:'video',coverOrientation:'portrait',author:nullable(first(value.author,value.source_name,value.source)),url:`${root}${paths.detail}#${encodeURIComponent(id)}`,coverUrl:proxyImage(text(first(value.playlet_poster,value.cover_url,value.vertical_poster,value.poster,value.cover,value.image,value.pic,value.thumbnail))),description:nullable(first(value.description,value.desc,value.intro)),language:'zh-CN',status:'unknown',access:'unknown',wordCount:null,chapterCount:countHint(latest),publishedAt:null,updatedAt:null,latestChapter:latest?{id:`playlet:${id}:latest`,title:latest,url:null,updatedAt:null}:null,categories:[],tags:[],attributes:[]});}
function pickList(value:unknown):Json[]{if(Array.isArray(value))return value.map(normalize);if(!isObject(value))return[];for(const candidate of[value.list,value.results,value.data,value.items,value.videos,value.vid_list,value.video_list,value.feed,value.playlet]){const found=pickList(candidate);if(found.length)return found;}return[];}function normalize(value:unknown):Json{if(!isObject(value))return{};if(isObject(value.content))return value.content;if(isObject(value.data)&&isObject(value.data.content))return value.data.content;return value;}function episode(value:unknown,index=0):Episode|null{if(typeof value==='string'||typeof value==='number'){const id=text(value);return id?{id,title:`第 ${index+1} 集`}:null;}if(!isObject(value))return null;const id=text(first(value.vid,value.video_id,value.videoId,value.id));if(!id)return null;return{id,title:text(first(value.title,value.name,value.episode_title,value.episode))||`第 ${index+1} 集`};}function pickUrl(value:unknown):string{if(typeof value==='string')return safeUrl(value)?value:'';if(Array.isArray(value)){for(const item of value){const found=pickUrl(item);if(found)return found;}return'';}if(!isObject(value))return'';const clarity=first(value.clarityUrl,value.clarity_url);for(const candidate of[clarity,value.video_src,value.play_url,value.url,value.video_url,value.src]){const found=pickUrl(candidate);if(found)return found;}return'';}
function nativeId(value:unknown){const id=text(value);return /^[\w-]+$/u.test(id)?id:null;}function contentId(id:string){const value=/^playlet:([\w-]+)$/u.exec(id)?.[1];if(!value)throw new Error('Content ID is invalid.');return value;}function chapterVid(id:string,content:string){const value=new RegExp(`^playlet:${content}:([\\w-]+)$`,'u').exec(id)?.[1];if(!value)throw new Error('Chapter ID is invalid.');return value;}function proxyImage(url:string){return safeUrl(url)?requireContext().resource.proxy({kind:'image',url,headers:{Referer:`${root}/`}}):null;}function safeUrl(value:string){try{return['http:','https:'].includes(new URL(value).protocol);}catch{return false;}}function countHint(value:string|null){const count=Number(value?.match(/\d+/u)?.[0]);return Number.isSafeInteger(count)?count:null;}function cursorPage(cursor:string|null,target:string){if(cursor===null)return 1;const page=Number(cursor.startsWith(`${target}:`)?cursor.slice(target.length+1):'');if(!Number.isSafeInteger(page)||page<2)throw new Error('Cursor is invalid.');return page;}function validateCursor(cursor:string,target:string){if(cursor!==`${target}:2`)throw new Error('Cursor is invalid.');}function first(...values:unknown[]){return values.find(value=>value!==null&&value!==undefined&&value!=='')??'';}function asArray(value:unknown){return Array.isArray(value)?value:[];}function isObject(value:unknown):value is Json{return value!==null&&typeof value==='object'&&!Array.isArray(value);}function text(value:unknown){return typeof value==='string'?value.trim():typeof value==='number'?String(value):'';}function nullable(value:unknown){return text(value)||null;}function notNull<T>(value:T|null):value is T{return value!==null;}function clamp(value:number){return Math.max(1,Math.min(50,Math.floor(value)));}function frozen<T>(value:T):T{return Object.freeze(value);}function requireContext(){if(!context)throw new Error('Source is not activated.');return context;}
