/**
 * 易听音乐网原生数据源。
 *
 * 职责：直接解析 eev3 榜单、检索、歌曲页，并提交站点自带的 CSRF 人机确认。
 * 生命周期：activate 注入 Runtime；仅在当前插件进程内保存站点响应 Cookie。
 * IO：页面与播放 POST 走 ctx.http，封面和音频经 ctx.resource.proxy。
 * 稳定标识：使用 /mp3/{slug}.html 中的站点歌曲 slug。
 */
import{load}from'cheerio';import type{MgReadPluginContext}from'@mgread/source-api';type Context=MgReadPluginContext;
const base='https://www.eev3.com',ua='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/92.0.4515.131 Safari/537.36',categories=Object.freeze([['top','TOP榜单'],['new','新歌榜'],['djwuqu','DJ舞曲'],['douyin','抖音热歌榜'],['kuaishou','快手热歌榜'],['hot','网络红歌榜'],['ystop','影视金曲榜'],['yytop','粤语金曲榜'],['ustop','欧美金曲榜'],['gfhot','古风音乐榜'],['wlhot','网红新歌榜'],['blhot','80后热歌榜'],['sctop','说唱先锋榜'],['dytop','电音热歌榜'],['cztop','车载歌曲榜'],['newacg','ACG新歌榜'],['krtop','韩国排行榜'],['jptop','日本排行榜']]as const);let context:Context|undefined,cookie='';
export async function activate(next:Context):Promise<void>{context=next;cookie='';next.log.info('source_activated');}
export async function search(request:{query:string;cursor:string|null;pageSize:number}){if(request.cursor!==null)throw new Error('Search cursor is unsupported.');const query=request.query.trim();if(query==='')return frozen({items:[],nextCursor:null,totalCount:0});const values=parseSongs(await getPage(`${base}/so/${encodeURIComponent(query)}.html`)).slice(0,clamp(request.pageSize));return frozen({items:values,nextCursor:null,totalCount:null});}
export async function searchSuggestions(_request:{cursor:string|null;pageSize:number}){return frozen({items:[],nextCursor:null});}
export async function discover(request:{target:string|null;cursor:string|null;collectionId:string|null;pageSize:number}){if(request.target===null){if(request.cursor!==null||request.collectionId!==null)throw new Error('Initial discovery request is invalid.');return frozen({kind:'document'as const,document:{components:[{type:'section',id:'audio-categories',title:'音乐榜单',subtitle:'按榜单浏览',icon:'audio',children:[{type:'categoryCollection',id:'audio-categories-list',layout:'chips',categories:categories.map(([id,title])=>({id,title,target:`category:${id}`,count:null,url:null,icon:'audio'}))}]}]}});}const category=categories.find(([id])=>request.target===`category:${id}`);if(category===undefined)throw new Error('Discovery target is invalid.');const page=cursorPage(request.cursor,request.target),limit=clamp(request.pageSize),[id,title]=category,url=page===1?`${base}/list/${id}.html`:`${base}/list/${id}/${page}.html`,values=parseSongs(await getPage(url)).slice(0,limit),collectionId=`audio:${id}`,items=values.map(content=>frozen({content,rank:null,metric:null,recommendation:null})),continuation=values.length>=limit?frozen({target:request.target,cursor:`${request.target}:${page+1}`}):null;if(request.collectionId!==null){if(request.collectionId!==collectionId)throw new Error('Discovery collection is invalid.');return frozen({kind:'append'as const,collectionId,items,continuation});}return frozen({kind:'document'as const,document:{components:[{type:'section',id:`${collectionId}:section`,title,subtitle:null,icon:'audio',children:[{type:'contentCollection',id:collectionId,layout:'coverGrid',items,continuation}]}]}});}
export async function getDetail(request:{id:string}){const slug=contentId(request.id),url=songUrl(slug),$=load(await getPage(url)),rawTitle=clean($('title').first().text()).replace(/\s*[-–—|]\s*易听音乐网.*$/u,'').replace(/\[Mp3_Lrc\].*$/u,''),parsed=parseTitle(rawTitle),cover=$('#mcover,.djpic img').first().attr('src')??'',author=parsed.author||clean($('.play_singer .name a').first().text()),album=$('.sm').toArray().map(node=>clean($(node).text())).find(value=>value.includes('所属专辑')||value.includes('专辑'))??'',item=summary(slug,parsed.name||rawTitle,author,cover);return frozen({...item,description:album||null,aliases:[],catalogUrl:url});}
export async function getChapters(request:{id:string}){const slug=contentId(request.id),$=load(await getPage(songUrl(slug))),title=clean($('title').first().text()).replace(/\s*[-–—|]\s*易听音乐网.*$/u,'')||'播放',chapter=frozen({id:`audio:${encodeKey(slug)}:main`,title,order:0,url:songUrl(slug),volumeTitle:'单曲',wordCount:null,updatedAt:null,isLocked:null,attributes:[]});return frozen({items:[chapter],groups:[frozen({id:`group:${encodeKey(slug)}:single`,title:'单曲',order:0,episodes:[chapter]})]});}
export async function getContent(request:{id:string;chapterId:string}){const slug=contentId(request.id);if(request.chapterId!==`audio:${encodeKey(slug)}:main`)throw new Error('Chapter ID is invalid.');const page=songUrl(slug);await getPage(page);const body=new URLSearchParams({id:slug,type:'music'}),response=await httpRequest(`${base}/js/play.php`,{method:'POST',headers:requestHeaders(page,'application/x-www-form-urlencoded; charset=UTF-8'),body:body.toString()}),value:unknown=await response.json();if(!isObject(value))throw new Error('Playback response is invalid.');const upstream=text(value.url);if(!safeUrl(upstream))throw new Error('Audio address is unavailable.');const mediaHeaders={Referer:page,'User-Agent':ua};return frozen({chapterId:request.chapterId,contentKind:'audio',title:null,updatedAt:null,text:null,pages:[],media:{url:requireContext().resource.proxy({kind:'audio',url:upstream,headers:mediaHeaders}),resourceType:'audio',resourcePolicy:'sessionOnly',expiresAt:null,mimeType:mime(upstream),headers:mediaHeaders}});}
async function getPage(url:string){let response=await httpRequest(url,{headers:requestHeaders(`${base}/`)}),html=await response.text();if(isVerify(html)){const token=/name=["']csrf_token["'][^>]*value=["']([^"']+)/iu.exec(html)?.[1];if(!token)throw new Error('Verification token is unavailable.');const body=new URLSearchParams({csrf_token:token,human_check:'on'});response=await httpRequest(url,{method:'POST',headers:requestHeaders(url,'application/x-www-form-urlencoded'),body:body.toString()});html=await response.text();if(isVerify(html)){response=await httpRequest(url,{headers:requestHeaders(`${base}/`)});html=await response.text();}}if(isVerify(html))throw new Error('Source verification was not accepted.');return html;}
async function httpRequest(url:string,init:RequestInit){const response=await requireContext().http.fetch(url,init);updateCookie(response.headers);if(!response.ok)throw new Error('Source request failed.');return response;}function requestHeaders(referer:string,contentType?:string){return{Accept:'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',...(contentType?{'Content-Type':contentType}:{}),...(cookie?{Cookie:cookie}:{}),Referer:referer,'User-Agent':ua,'X-Requested-With':contentType?.includes('charset')?'XMLHttpRequest':''};}function updateCookie(value:Headers){const raw=value.get('set-cookie');if(raw)cookie=raw.split(';')[0]??cookie;}
function parseSongs(html:string){const $=load(html),values=new Map<string,ReturnType<typeof summary>>();$('a[href^="/mp3/"]').each((_,node)=>{const href=$(node).attr('href')??'',slug=/\/mp3\/([^/.]+)\.html/u.exec(href)?.[1];if(!slug||values.has(slug))return;const parsed=parseTitle($(node).attr('title')??$(node).text());if(parsed.name!=='')values.set(slug,summary(slug,parsed.name,parsed.author,''));});return[...values.values()];}
function parseTitle(value:string){const title=clean(value),match=/^(.+?)《(.+?)》/u.exec(title);return match?{name:clean(match[2]??''),author:clean(match[1]??'')}:{name:title,author:''};}function summary(slug:string,title:string,author:string,cover:string){const id=encodeKey(slug);return frozen({id:`audio:${id}`,title,contentKind:'audio',coverOrientation:'portrait',author:author||null,url:songUrl(slug),coverUrl:proxyImage(cover),description:null,language:'zh-CN',status:'completed',access:'free',wordCount:null,chapterCount:1,publishedAt:null,updatedAt:null,latestChapter:{id:`audio:${id}:main`,title:'播放',url:null,updatedAt:null},categories:['音乐'],tags:[],attributes:[]});}
function songUrl(slug:string){return`${base}/mp3/${encodeURIComponent(slug)}.html`;}function contentId(id:string){const value=/^audio:([^:]+)$/u.exec(id)?.[1];if(value===undefined)throw new Error('Content ID is invalid.');return decodeKey(value);}function proxyImage(value:string){if(value==='')return null;let url:string;try{url=new URL(value,base).toString();}catch{return null;}return requireContext().resource.proxy({kind:'image',url,headers:{Referer:`${base}/`}});}function isVerify(value:string){return value.includes('安全人机验证')&&value.includes('csrf_token');}function safeUrl(value:string){try{const url=new URL(value);return(url.protocol==='https:'||url.protocol==='http:')&&url.username===''&&url.password==='';}catch{return false;}}function mime(url:string){return/\.m4a(?:$|[?#])/iu.test(url)?'audio/mp4':/\.aac(?:$|[?#])/iu.test(url)?'audio/aac':'audio/mpeg';}function encodeKey(value:string){return Buffer.from(value,'utf8').toString('base64url');}function decodeKey(value:string){if(!/^[A-Za-z0-9_-]+$/u.test(value))throw new Error('Source key is invalid.');return Buffer.from(value,'base64url').toString('utf8');}function clean(value:string){return value.replace(/[\s\u00a0]+/gu,' ').trim();}function cursorPage(cursor:string|null,target:string){if(cursor===null)return 1;const raw=cursor.startsWith(`${target}:`)?cursor.slice(target.length+1):'',page=Number(raw);if(!Number.isSafeInteger(page)||page<2||page>1000)throw new Error('Cursor is invalid.');return page;}function clamp(value:number){return Math.max(1,Math.min(50,Math.floor(value)));}function isObject(value:unknown):value is Record<string,unknown>{return value!==null&&typeof value==='object'&&!Array.isArray(value);}function text(value:unknown){return typeof value==='string'?value.trim():'';}function frozen<T>(value:T):T{return Object.freeze(value);}function requireContext():Context{if(context===undefined)throw new Error('Source is not activated.');return context;}
