name: mg_read
description: "Main Flutter application for MgRead."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  novel_reader_ui:
    path: ../mg_read_reader_ui

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
