/** Plugin API v1 adapter for the repository source `xtyxsw-org`. */
import type {ChaptersRequest,ContentReferenceRequest,ContentRequest,DiscoverRequest,MgReadPluginContext,SearchRequest,SearchSuggestionsRequest} from './contracts.js';
import {categories,TianyueSource} from './source.js';
let context:MgReadPluginContext|undefined;let source:TianyueSource|undefined;
export async function activate(next:MgReadPluginContext):Promise<void>{context=next;next.log.info('source_activated');}
export async function search(request:SearchRequest){if(request.cursor!==null)throw new Error('Search cursor is unsupported.');return invoke('search',async active=>Object.freeze({items:Object.freeze((await active.search(request.query)).slice(0,request.pageSize)),nextCursor:null,totalCount:null}));}
export async function discover(request:DiscoverRequest){if(request.target===null){if(request.cursor!==null||request.collectionId!==null)throw new Error('Initial discovery request is invalid.');const result=await invoke('discover_home',active=>active.discover('new',1));return categoriesDocument(result.items.slice(0,Math.min(request.pageSize,10)));}const categoryId=/^category:([a-z-]+)$/u.exec(request.target)?.[1];if(categoryId===undefined)throw new Error('Discovery target is invalid.');const page=cursorPage(request.cursor,`category:${categoryId}`);const result=await invoke('discover',active=>active.discover(categoryId,page));const items=Object.freeze(result.items.slice(0,request.pageSize).map(content=>Object.freeze({content,rank:null,metric:null,recommendation:null})));const collectionId=`category-books:${categoryId}`;const continuation=result.hasNext?Object.freeze({target:request.target,cursor:`category:${categoryId}:${page+1}`}):null;if(request.collectionId!==null){if(request.collectionId!==collectionId)throw new Error('Discovery collection is invalid.');return Object.freeze({kind:'append' as const,collectionId,items,continuation});}return Object.freeze({kind:'document' as const,document:{components:Object.freeze([{type:'section' as const,id:`${collectionId}-section`,title:categories.find(([id])=>id===categoryId)?.[1]??'分类',subtitle:null,children:Object.freeze([{type:'contentCollection' as const,id:collectionId,layout:'list' as const,items,continuation}])}])}});}
export async function searchSuggestions(_request:SearchSuggestionsRequest){return Object.freeze({items:Object.freeze([]),nextCursor:null});}
export async function getDetail(request:ContentReferenceRequest){return invoke('get_detail',active=>active.getDetail(request.id));}
export async function getChapters(request:ChaptersRequest){return invoke('get_chapters',active=>active.getChapters(request.id));}
export async function getContent(request:ContentRequest){return invoke('get_content',active=>active.getContent(request.id,request.chapterId));}
function categoriesDocument(content:readonly Awaited<ReturnType<TianyueSource['discover']>>['items'][number][]){const items=Object.freeze(content.map(value=>Object.freeze({content:value,rank:null,metric:null,recommendation:null})));return Object.freeze({kind:'document' as const,document:{components:Object.freeze([...(items.length===0?[]:[{type:'section' as const,id:'latest-section',title:'新书入库',subtitle:'官网新近收录作品',icon:'newRelease' as const,children:Object.freeze([{type:'contentCollection' as const,id:'latest-books',layout:'shelf' as const,items,continuation:null}])}]),{type:'section' as const,id:'categories-section',title:'分类与榜单',subtitle:'按题材或热度继续发现',icon:'explore' as const,children:Object.freeze([{type:'categoryCollection' as const,id:'categories',layout:'chips' as const,categories:Object.freeze(categories.map(([id,title])=>Object.freeze({id,title,target:`category:${id}`,count:null,url:null,icon:id==='visits'?'hot':id==='votes'?'recommendation':id==='favorites'?'star':id==='new'?'newRelease':id.includes('romance')?'romance':id==='fantasy'||id==='fantasy-west'?'fantasy':id==='wuxia'||id==='xianxia'?'wuxia':id==='urban'?'urban':id==='history'?'history':id==='military'?'military':id==='mystery'?'mystery':id==='game'?'game':id==='science-fiction'?'scienceFiction':id==='sports'?'sports':'category'}))) }])}])}});}
function requireSource(){if(context===undefined)throw new Error('Source is not activated.');return source??=new TianyueSource(context);}
async function invoke<T>(operation:string,action:(active:TianyueSource)=>Promise<T>):Promise<T>{if(context===undefined)throw new Error('Source is not activated.');context.log.info(`source_${operation}_started`);try{const result=await action(requireSource());context.log.info(`source_${operation}_completed`);return result;}catch(error){context.log.warn(`source_${operation}_failed`);throw error;}}
function cursorPage(cursor:string|null,scope:string){if(cursor===null)return 1;const escaped=scope.replace(/[.*+?^${}()|[\]\\]/gu,'\\$&');const page=Number(new RegExp(`^${escaped}:(\\d+)$`,'u').exec(cursor)?.[1]);if(!Number.isSafeInteger(page)||page<2||page>100)throw new Error('Cursor is invalid.');return page;}
