import assert from'node:assert/strict';import test from'node:test';import*as plugin from'../dist/index.mjs';test('UAA audio API yields albums, stable chapters and proxied audio',async()=>{const resources=[];await plugin.activate({log:{info(){},warn(){}},resource:{proxy(v){resources.push(v);return`http://127.0.0.1/resource/${resources.length}`;}},http:{async fetch(input){const url=String(input);if(url.includes('/catalog/'))return Response.json({result:'success',model:{menus:[{id:'10000002',title:'第一集'}]}});if(url.includes('/chapter?'))return Response.json({result:'success',model:{title:'第一集',url:'https://media.example/episode.mp3'}});if(url.includes('/intro?'))return Response.json({result:'success',model:{id:'10000001',title:'测试专辑',authors:'主播',coverUrl:'https://img.example/cover.jpg',chapterCount:1}});return Response.json({result:'success',model:{data:[{id:'10000001',title:'测试专辑',authors:'主播',coverUrl:'https://img.example/cover.jpg',chapterCount:1}],totalPage:1,totalCount:1}});}}});const listing=await plugin.discover({target:'channel:latest',cursor:null,collectionId:null,pageSize:5});const item=listing.document.components[0].children[0].items[0].content;assert.equal(item.id,'audio:10000001');const detail=await plugin.getDetail({id:item.id});assert.equal(detail.author,'主播');const chapters=await plugin.getChapters({id:item.id});assert.equal(chapters.items[0].id,'audio:10000001:10000002');const content=await plugin.getContent({id:item.id,chapterId:chapters.items[0].id});assert.equal(content.media.resourceType,'audio');assert.equal(resources.find(v=>v.kind==='audio').url,'https://media.example/episode.mp3');});

function discoveryCollections(result) {const found=[]; const visit=node=>{if(node.type==='contentCollection')found.push(node);for(const child of node.children??[])visit(child);};for(const node of result.document?.components??[])visit(node);return found;}
test('discovery previews and rankings preserve upstream paging and rank',async()=>{
 await plugin.activate({log:{info(){}},resource:{proxy:v=>v.url},http:{fetch:async()=>Response.json({result:'success',model:{data:Array.from({length:7},(_,i)=>({id:String(10000001+i),title:'Album '+i})),totalPage:1,totalCount:7}})}});
 const root=await plugin.discover({target:null,cursor:null,collectionId:null,pageSize:3});const list=discoveryCollections(root)[1];assert.equal(list.layout,'compact');assert.equal(list.items[0].rank,1);
 const tail=await plugin.discover({...list.continuation,collectionId:list.id,pageSize:50});assert.equal(tail.items.length,4);assert.equal(tail.items[0].rank,4);assert.equal(tail.continuation,null);
 await assert.rejects(plugin.discover({target:'channel:latest',cursor:'channel:weekly:1:3',collectionId:null,pageSize:3}));
});
test('complete ranking arrays finish locally without requesting a duplicate second page',async()=>{
 const pages=[];await plugin.activate({log:{info(){}},resource:{proxy:r=>r.url},http:{fetch:async input=>{pages.push(new URL(input).searchParams.get('page'));return Response.json({result:'success',model:Array.from({length:100},(_,i)=>({id:String(10000000+i),title:'Rank '+i,chapterCount:1}))});}}});
 const first=await plugin.discover({target:'channel:weekly',cursor:null,collectionId:null,pageSize:50});const list=first.document.components[0].children[0];
 const last=await plugin.discover({...list.continuation,collectionId:list.id,pageSize:50});assert.equal(last.items.length,50);assert.equal(last.continuation,null);assert.equal(last.items.at(-1).rank,100);assert.deepEqual(pages,['1','1']);
});
