/**
 * 酷狗音乐原生数据源。
 *
 * 职责：直接读取酷狗搜索、榜单及歌曲播放信息，不执行旧书源脚本。
 * 生命周期：activate 注入 Runtime；不保存账号或 Cookie。
 * IO：所有 JSON 请求走 ctx.http；封面和音频经 ctx.resource.proxy。
 * 稳定标识：歌曲使用酷狗 FileHash，章节 ID 不包含播放地址。
 */
import type { MgReadPluginContext } from '@mgread/source-api';
type Json=Record<string,unknown>;type Context=MgReadPluginContext;
const origin='https://www.kugou.com',headers=Object.freeze({Accept:'application/json,text/plain,*/*',Referer:`${origin}/`,'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}),channels=Object.freeze([['top500','TOP500','8888'],['rising','飙升榜','6666'],['network','网络热歌榜','82831']]as const);let context:Context|undefined;
export async function activate(next:Context):Promise<void>{context=next;next.log.info('source_activated');}
export async function search(request:{query:string;cursor:string|null;pageSize:number}){const query=request.query.trim();if(query==='')return frozen({items:[],nextCursor:null,totalCount:0});const page=cursorPage(request.cursor,'search'),size=clamp(request.pageSize),json=await fetchJson(`https://songsearch.kugou.com/song_search_v2?keyword=${encodeURIComponent(query)}&page=${page}&pagesize=${size}&userid=0&platform=WebFilter&filter=2&iscorrection=1&privilege_filter=0&area_code=1`),data=object(json.data),items=records(data.lists).map(songSummary).filter(notNull),totalCount=nonNegative(data.total);return frozen({items,nextCursor:totalCount!==null?page*size<totalCount?`search:${page+1}`:null:items.length>=size?`search:${page+1}`:null,totalCount});}
export async function searchSuggestions(_request:{cursor:string|null;pageSize:number}){return frozen({items:[],nextCursor:null});}
export async function discover(request:{target:string|null;cursor:string|null;collectionId:string|null;pageSize:number}){if(request.target===null){if(request.cursor!==null||request.collectionId!==null)throw new Error('Initial discovery request is invalid.');return frozen({kind:'document'as const,document:{components:[{type:'section',id:'kugou-charts',title:'酷狗音乐',subtitle:'官方榜单',icon:'audio',children:[{type:'categoryCollection',id:'kugou-chart-list',layout:'chips',categories:channels.map(([id,title])=>({id,title,target:`chart:${id}`,count:null,url:null,icon:'ranking'}))}]}]}});}const channel=channels.find(([id])=>request.target===`chart:${id}`);if(channel===undefined)throw new Error('Discovery target is invalid.');const page=cursorPage(request.cursor,`chart:${channel[0]}`),size=clamp(request.pageSize),json=await fetchJson(`http://mobilecdnbj.kugou.com/api/v3/rank/song?version=9108&ranktype=1&plat=0&pagesize=${size}&area_code=1&page=${page}&rankid=${channel[2]}&with_res_tag=0&show_portrait_mv=1`),values=records(object(json.data).info).map(songSummary).filter(notNull),collectionId=`audio:${channel[0]}`,items=values.map(content=>frozen({content,rank:null,metric:null,recommendation:null})),continuation=values.length>=size?frozen({target:request.target,cursor:`chart:${channel[0]}:${page+1}`}):null;if(request.collectionId!==null){if(request.collectionId!==collectionId)throw new Error('Discovery collection is invalid.');return frozen({kind:'append'as const,collectionId,items,continuation});}return frozen({kind:'document'as const,document:{components:[{type:'section',id:`${collectionId}:section`,title:channel[1],subtitle:null,icon:'audio',children:[{type:'contentCollection',id:collectionId,layout:'coverGrid',items,continuation}]}]}});}
export async function getDetail(request:{id:string}){const hash=contentId(request.id),data=await loadPlayback(hash),item=detailSummary(hash,data);return frozen({...item,aliases:[],catalogUrl:`${origin}/song/#hash=${hash}`});}
export async function getChapters(request:{id:string}){const hash=contentId(request.id),detail=await getDetail(request),chapter=frozen({id:`audio:${hash}:main`,title:`${detail.title}${detail.author?` - ${detail.author}`:''}`,order:0,url:null,volumeTitle:'单曲',wordCount:null,updatedAt:null,isLocked:null,attributes:[]});return frozen({items:[chapter],groups:[frozen({id:`group:audio:${hash}`,title:'单曲',order:0,episodes:[chapter]})]});}
export async function getContent(request:{id:string;chapterId:string}){const hash=contentId(request.id);if(request.chapterId!==`audio:${hash}:main`)throw new Error('Chapter ID is invalid.');const data=await loadPlayback(hash),upstream=text(first(data.play_url,data.playUrl,data.url));if(!safeUrl(upstream))throw new Error('Audio address is unavailable.');const mediaHeaders={Referer:`${origin}/`,'User-Agent':headers['User-Agent']};return frozen({chapterId:request.chapterId,contentKind:'audio',title:nullable(first(data.song_name,data.audio_name)),updatedAt:null,text:null,pages:[],media:{url:requireContext().resource.proxy({kind:'audio',url:upstream,headers:mediaHeaders}),resourceType:'audio',resourcePolicy:'sessionOnly',expiresAt:null,mimeType:/\.flac(?:$|[?#])/iu.test(upstream)?'audio/flac':'audio/mpeg',headers:mediaHeaders}});}
async function loadPlayback(hash:string){const json=await fetchJson(`https://wwwapi.kugou.com/yy/index.php?r=play/getdata&hash=${encodeURIComponent(hash)}`),data=object(json.data);if(Object.keys(data).length===0)throw new Error('Song playback is unavailable.');return data;}async function fetchJson(url:string):Promise<Json>{const response=await requireContext().http.fetch(url,{headers});if(!response.ok)throw new Error('Source request failed.');const value:unknown=await response.json();if(!isObject(value))throw new Error('Source response is invalid.');return value;}
function songSummary(song:Json){const hash=hashId(first(song.FileHash,song.hash,song.filehash));if(hash===null)return null;const title=text(first(song.SongName,song.OriSongName,song.songname,song.song_name,song.FileName,song.filename))||hash,filename=text(first(song.filename,song.FileName)),author=text(first(song.SingerName,song.singername))||filename.split(' - ')[0]||'',album=text(first(song.AlbumName,song.album_name)),duration=durationText(first(song.Duration,song.duration)),cover=coverUrl(text(first(song.Image,song.AlbumImage,song.img,song.album_img,song.album_sizable_cover,object(song.trans_param).union_cover)));return frozen({id:`audio:${hash}`,title,contentKind:'audio',coverOrientation:'square',author:author||null,url:`${origin}/song/#hash=${hash}`,coverUrl:proxyImage(cover),description:[album,duration].filter(Boolean).join(' · ')||null,language:null,status:'completed',access:number(first(song.PayType,song.pay_type,song.feetype))>0?'paid':'unknown',wordCount:null,chapterCount:1,publishedAt:null,updatedAt:null,latestChapter:{id:`audio:${hash}:main`,title:duration||'播放',url:null,updatedAt:null},categories:['音乐'],tags:[],attributes:[]});}
function detailSummary(hash:string,data:Json){const duration=durationText(number(first(data.timelength,data.timeLength))/1000),title=text(first(data.song_name,data.audio_name))||hash;return frozen({id:`audio:${hash}`,title,contentKind:'audio',coverOrientation:'square',author:nullable(first(data.author_name,data.author)),url:`${origin}/song/#hash=${hash}`,coverUrl:proxyImage(coverUrl(text(first(data.img,data.album_img)))),description:[text(data.album_name),duration].filter(Boolean).join(' · ')||null,language:null,status:'completed',access:'unknown',wordCount:null,chapterCount:1,publishedAt:null,updatedAt:null,latestChapter:{id:`audio:${hash}:main`,title:duration||'播放',url:null,updatedAt:null},categories:['音乐'],tags:[],attributes:[]});}
function hashId(value:unknown){const hash=text(value).toUpperCase();return /^[A-F0-9]{16,128}$/u.test(hash)?hash:null;}function contentId(id:string){const hash=/^audio:([A-F0-9]{16,128})$/u.exec(id)?.[1];if(hash===undefined)throw new Error('Content ID is invalid.');return hash;}function durationText(value:unknown){const seconds=Math.floor(number(value));if(seconds<=0)return'';return`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;}function coverUrl(value:string){return value.replaceAll('{size}','400');}function proxyImage(value:string){if(!safeUrl(value))return null;return requireContext().resource.proxy({kind:'image',url:value,headers:{Referer:`${origin}/`}});}function safeUrl(value:string){try{const url=new URL(value);return(url.protocol==='https:'||url.protocol==='http:')&&url.username===''&&url.password==='';}catch{return false;}}function cursorPage(cursor:string|null,target:string){if(cursor===null)return 1;const raw=cursor.startsWith(`${target}:`)?cursor.slice(target.length+1):'',page=Number(raw);if(!Number.isSafeInteger(page)||page<2||page>1000)throw new Error('Cursor is invalid.');return page;}
function nonNegative(value:unknown){const n=Number(value);return Number.isSafeInteger(n)&&n>=0?n:null;}function first(...values:unknown[]){return values.find(value=>value!==null&&value!==undefined&&value!=='')??'';}function records(value:unknown):Json[]{return Array.isArray(value)?value.filter(isObject):[];}function object(value:unknown):Json{return isObject(value)?value:{};}function isObject(value:unknown):value is Json{return value!==null&&typeof value==='object'&&!Array.isArray(value);}function text(value:unknown){return typeof value==='string'?value.replace(/<[^>]+>/gu,'').trim():typeof value==='number'?String(value):'';}function number(value:unknown){const result=Number(value);return Number.isFinite(result)?result:0;}function nullable(value:unknown){const result=text(value);return result===''?null:result;}function notNull<T>(value:T|null):value is T{return value!==null;}function clamp(value:number){return Math.max(1,Math.min(50,Math.floor(value)));}function frozen<T>(value:T):T{return Object.freeze(value);}function requireContext():Context{if(context===undefined)throw new Error('Source is not activated.');return context;}
