/**
 * 275听书网原生数据源。
 *
 * 职责：直接解析 i275 移动站的首页、检索、详情、目录和音频地址。
 * 生命周期：activate 注入 Runtime 上下文；不保留页面或登录状态。
 * IO：HTML 走 ctx.http，封面与音频经 ctx.resource.proxy。
 * 稳定标识：有声书和章节使用 /book/、/play/ 路径中的数字 ID。
 */
import{load}from'cheerio';import type{MgReadPluginContext}from'@mgread/source-api';type Context=MgReadPluginContext;
const base='https://m.i275.com',ua='Mozilla/5.0 (Linux; Android 11; Pixel 5) AppleWebKit/537.36 Chrome/90.0.4430.91 Mobile Safari/537.36';let context:Context|undefined;
export async function activate(next:Context):Promise<void>{context=next;next.log.info('source_activated');}
export async function search(request:{query:string;cursor:string|null;pageSize:number}){const query=request.query.trim();if(query==='')return frozen({items:[],nextCursor:null,totalCount:0});const page=cursorPage(request.cursor,'search'),limit=clamp(request.pageSize),values=parseBooks(await fetchText(`${base}/search.php?q=${encodeURIComponent(query)}&page=${page}`)).slice(0,limit);return frozen({items:values,nextCursor:values.length>=limit?`search:${page+1}`:null,totalCount:null});}
export async function searchSuggestions(_request:{cursor:string|null;pageSize:number}){return frozen({items:[],nextCursor:null});}
export async function discover(request:{target:string|null;cursor:string|null;collectionId:string|null;pageSize:number}){if(request.target===null){if(request.cursor!==null||request.collectionId!==null)throw new Error('Initial discovery request is invalid.');const values=parseBooks(await fetchText(`${base}/`)).slice(0,clamp(request.pageSize)),items=values.map(content=>frozen({content,rank:null,metric:null,recommendation:null}));return frozen({kind:'document'as const,document:{components:[{type:'section',id:'audio-home',title:'有声小说',subtitle:null,icon:'audio',children:[{type:'contentCollection',id:'audio-home-list',layout:'coverGrid',items,continuation:null}]}]}});}throw new Error('Discovery target is invalid.');}
export async function getDetail(request:{id:string}){const id=contentId(request.id),url=bookUrl(id),$=load(await fetchText(url)),title=clean($('h1.text-2xl').first().text())||clean($('title').first().text()).replace(/\s*-\s*.*$/u,''),cover=$('.bg-white .w-32 img,.bg-white .w-48 img,img[alt]').first().attr('src')??'',description=clean($('.line-clamp-3').first().text()),meta=$('.mt-2 p').toArray().map(node=>clean($(node).text())),status=meta.find(value=>value.startsWith('状态：'))?.slice(3).trim()??'',chapters=parseChapters($,id),item=summary(id,title,cover,description);return frozen({...item,status:status.includes('完结')?'completed':'unknown',chapterCount:chapters.length||null,latestChapter:chapters.length===0?null:{id:chapters.at(-1)?.id??null,title:chapters.at(-1)?.title??'',url:null,updatedAt:null},aliases:[],catalogUrl:url});}
export async function getChapters(request:{id:string}){const id=contentId(request.id),$=load(await fetchText(bookUrl(id))),items=parseChapters($,id);if(items.length===0)throw new Error('No audio chapters found.');return frozen({items,groups:[frozen({id:`group:${id}:default`,title:'默认线路',order:0,episodes:items})]});}
export async function getContent(request:{id:string;chapterId:string}){const id=contentId(request.id),chapter=parseChapterId(request.chapterId,id),page=chapterUrl(id,chapter),html=await fetchText(page,page),$=load(html),candidate=audioFromHtml(html)||$('audio source,audio').first().attr('src')||$('audio[data-src]').first().attr('data-src')||$('audio[data-url]').first().attr('data-url')||'',upstream=absolute(candidate);if(upstream===null||!isAudio(upstream))throw new Error('Audio address is unavailable.');const mediaHeaders={Origin:base,Referer:page,'User-Agent':ua};return frozen({chapterId:request.chapterId,contentKind:'audio',title:null,updatedAt:null,text:null,pages:[],media:{url:requireContext().resource.proxy({kind:'audio',url:upstream,headers:mediaHeaders}),resourceType:'audio',resourcePolicy:'sessionOnly',expiresAt:null,mimeType:mime(upstream),headers:mediaHeaders}});}
async function fetchText(url:string,referer=`${base}/`){const response=await requireContext().http.fetch(url,{headers:{Accept:'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',Origin:base,Referer:referer,'User-Agent':ua}});if(!response.ok)throw new Error('Source request failed.');return response.text();}
function parseBooks(html:string){const $=load(html),values=new Map<string,ReturnType<typeof summary>>();$('a[href^="/book/"]').each((_,node)=>{const href=$(node).attr('href')??'',id=/\/book\/(\d+)\.html/u.exec(href)?.[1];if(id===undefined||values.has(id))return;const title=clean($(node).find('h3,.font-medium.text-sm,.font-medium').first().text())||clean($(node).find('img').first().attr('alt')??''),cover=$(node).find('img').first().attr('src')??'',description=clean($(node).find('.line-clamp-2').first().text());if(title!=='')values.set(id,summary(id,title,cover,description));});return[...values.values()];}
function parseChapters($:ReturnType<typeof load>,book:string){const values:{id:string;title:string}[]=[],seen=new Set<string>();$('a[href^="/play/"]').each((_,node)=>{const href=$(node).attr('href')??'',match=new RegExp(`/play/${book}/(\\d+)\\.html`,'u').exec(href),title=clean($(node).find('.text-sm.text-gray-700').first().text())||clean($(node).text());if(!match?.[1]||title===''||seen.has(match[1]))return;seen.add(match[1]);values.push({id:match[1],title});});return values.map((value,index)=>frozen({id:`audio:${book}:${value.id}`,title:value.title,order:index,url:chapterUrl(book,value.id),volumeTitle:'默认线路',wordCount:null,updatedAt:null,isLocked:null,attributes:[]}));}
function summary(id:string,title:string,cover:string,description:string){return frozen({id:`audio:${id}`,title,contentKind:'audio',coverOrientation:'portrait',author:null,url:bookUrl(id),coverUrl:proxyImage(cover),description:description||null,language:'zh-CN',status:'unknown',access:'free',wordCount:null,chapterCount:null,publishedAt:null,updatedAt:null,latestChapter:null,categories:['有声小说'],tags:[],attributes:[]});}
function audioFromHtml(html:string){const patterns=[/url\s*:\s*["']([^"']+\.(?:mp3|m4a|aac|flac|wav|ogg|opus|ape|wma)(?:\?[^"']*)?)["']/iu,/audio_url\s*[=:]\s*["']([^"']+)["']/iu,/file\s*[=:]\s*["']([^"']+)["']/iu,/(https?:\/\/[^"'<>\\\s]+\.(?:mp3|m4a|aac|flac|wav|ogg|opus|ape|wma)(?:\?[^"'<>\\\s]*)?)/iu];for(const pattern of patterns){const value=pattern.exec(html)?.[1];if(value)return value.replaceAll('\\/','/').replaceAll('\\u0026','&').replaceAll('\\x26','&').replaceAll('&amp;','&');}return'';}
function bookUrl(id:string){return`${base}/book/${id}.html`;}function chapterUrl(book:string,chapter:string){return`${base}/play/${book}/${chapter}.html`;}function contentId(id:string){const value=/^audio:(\d+)$/u.exec(id)?.[1];if(value===undefined)throw new Error('Content ID is invalid.');return value;}function parseChapterId(id:string,book:string){const value=new RegExp(`^audio:${book}:(\\d+)$`,'u').exec(id)?.[1];if(value===undefined)throw new Error('Chapter ID is invalid.');return value;}
function proxyImage(value:string){const url=absolute(value);return url===null?null:requireContext().resource.proxy({kind:'image',url,headers:{Referer:`${base}/`}});}function absolute(value:string){const raw=value.trim();if(raw==='')return null;try{return new URL(raw.replaceAll('\\/','/'),base).toString();}catch{return null;}}function isAudio(url:string){return/\.(?:mp3|m4a|aac|flac|wav|ogg|opus|ape|wma)(?:$|[?#])/iu.test(url);}function mime(url:string){if(/\.m4a(?:$|[?#])/iu.test(url))return'audio/mp4';if(/\.aac(?:$|[?#])/iu.test(url))return'audio/aac';if(/\.flac(?:$|[?#])/iu.test(url))return'audio/flac';return'audio/mpeg';}function clean(value:string){return value.replace(/\s+/gu,' ').trim();}function cursorPage(cursor:string|null,target:string){if(cursor===null)return 1;const raw=cursor.startsWith(`${target}:`)?cursor.slice(target.length+1):'',page=Number(raw);if(!Number.isSafeInteger(page)||page<2||page>1000)throw new Error('Cursor is invalid.');return page;}function clamp(value:number){return Math.max(1,Math.min(50,Math.floor(value)));}function frozen<T>(value:T):T{return Object.freeze(value);}function requireContext():Context{if(context===undefined)throw new Error('Source is not activated.');return context;}
