/**
 * First Edition mobile source.
 *
 * Protected HTML uses one Runtime-owned WebView page. Requests run through the
 * page's same-origin fetch, while verification visibility and native HTML stay
 * host-owned; Cookie, user-agent and platform handles never enter plugin code.
 */
import { Buffer } from 'node:buffer'; import * as cheerio from 'cheerio/slim'; import { PluginCache } from '@mgread/plugin-cache';
interface WebViewPage { navigate(url:string,options?:{readonly timeoutMs?:number}):Promise<void>; getHtml(options?:{readonly timeoutMs?:number}):Promise<string>; fetch(request:{readonly url:string;readonly method?:string;readonly headers?:Readonly<Record<string,string>>;readonly body?:string|null;readonly responseType?:'text'|'json'|'base64';readonly timeoutMs?:number}):Promise<{readonly status:number;readonly url:string;readonly headers:Readonly<Record<string,string>>;readonly body:unknown}>; waitForText(request:{readonly text:string;readonly scope?:'text'|'html';readonly timeoutMs:number}):Promise<{readonly url:string}>; getUrl(options?:{readonly timeoutMs?:number}):Promise<string>; show(options?:{readonly timeoutMs?:number}):Promise<void>; hide(options?:{readonly timeoutMs?:number}):Promise<void>; }
export interface Context { readonly cacheDir:string; readonly webview:{open(options?:{readonly visible?:boolean;readonly timeoutMs?:number}):Promise<WebViewPage>}; readonly http:{fetch(input:string|URL,init?:RequestInit):Promise<Response>}; readonly resource:{proxy(request:Record<string,unknown>):string}; readonly log:{debug(value:string):void;info(value:string):void;warn(value:string):void;error(value:string):void}; }
interface Summary { readonly id:string; readonly title:string; readonly contentKind:'novel'; readonly author:string|null; readonly url:string; readonly coverUrl:string|null; readonly description:string|null; readonly language:'zh-CN'; readonly status:'ongoing'|'completed'|'unknown'; readonly access:'free'; readonly wordCount:number|null; readonly chapterCount:number|null; readonly publishedAt:null; readonly updatedAt:null; readonly latestChapter:{readonly id:null;readonly title:string;readonly url:null;readonly updatedAt:null}|null; readonly categories:readonly string[]; readonly tags:readonly string[]; readonly attributes:readonly {readonly key:string;readonly label:string;readonly value:string}[]; }
const origin='https://m.diyibanzhu.me'; const browserTimeoutMs=120000; const listingPolicy=Object.freeze({namespace:'listing',staleAfterMs:10*60*1000,serveStaleWhileRevalidate:true}); const detailPolicy=Object.freeze({namespace:'detail',staleAfterMs:60*60*1000,allowStaleOnError:false}); const catalogPolicy=Object.freeze({namespace:'catalog',staleAfterMs:60*60*1000,allowStaleOnError:false});
export const categories=Object.freeze([['total','总人气榜','/book/rate_1.html','/book/1_16687_{P}.html'],['month','月人气榜','/book/rate_2.html','/book/2_16687_{P}.html'],['new','新书榜','/book/rate_3.html','/book/3_16687_{P}.html'],['words','字数榜','/book/rate_4.html','/book/4_16687_{P}.html'],['updates','最新更新','/book/index.html','/book/16687_{P}.html'],['fantasy','玄幻·奇幻','/wap.php?action=shuku&order=3&tid=4','/book/4_3_16687_{P}.html'],['martial','仙侠·武侠','/wap.php?action=shuku&order=3&tid=3','/book/3_3_16687_{P}.html'],['city','都市·言情','/wap.php?action=shuku&order=3&tid=2','/book/2_3_16687_{P}.html'],['history','穿越·历史','/wap.php?action=shuku&order=3&tid=1','/book/1_3_16687_{P}.html'],['scifi','科幻·灵异','/wap.php?action=shuku&order=3&tid=6','/book/6_3_16687_{P}.html'],['other','其他小说','/wap.php?action=shuku&order=3&tid=8','/book/8_3_16687_{P}.html']] as const);
export class DiyibanzhuSource {
  readonly #cache:PluginCache; #pagePromise:Promise<WebViewPage>|undefined; #readyPromise:Promise<void>|undefined; #browserTail:Promise<void>=Promise.resolve(); constructor(private readonly context:Context){this.#cache=new PluginCache(context.cacheDir);}
  async search(query:string){const url=new URL('/wap.php?action=search',origin);const html=await this.#browser(url,'POST',`objectType=2&wd=${encodeURIComponent(query)}`);return this.parseList(html,url);}
  async discover(id:string,page:number){const rule=categories.find(([key])=>key===id);if(rule===undefined)throw new Error('Unknown category.');const path=page===1?rule[2]:rule[3].replace('{P}',String(page));const url=new URL(path,origin);return this.parseList(await this.#cache.getOrFetchText(url,listingPolicy,()=>this.#browser(url,'GET',null)),url);}
  parseList(html:string,base:URL):readonly Summary[]{const $=cheerio.load(html);const seen=new Set<string>();const items:Summary[]=[];$('li.column-2').each((_,element)=>{const root=$(element);const link=root.find('a.name,.right a').first();const href=link.attr('href');const title=clean(link.text())??clean(root.find('.right .name').text());if(href===undefined||title===null)return;const url=new URL(href,base);if(!isBook(url)||seen.has(url.toString()))return;seen.add(url.toString());const info=clean(root.find('.info').text())??'';const author=clean(root.find('.author').text())??clean(/作者[：:]\s*(\S+)/u.exec(info)?.[1]);const latest=clean(root.find('.update a').text());const words=parseCount(root.find('.words').text());items.push(summary(url,title,author,null,null,words,latest,[]));});return Object.freeze(items);}
  async detail(id:string){const url=decode(id,'book');const html=await this.#cache.getOrFetchText(url,detailPolicy,()=>this.#browser(url,'GET',null));const $=cheerio.load(html);const title=clean($('.mod.detail .right h1,.detail h1').first().text());if(title===null)throw new Error('Detail title is missing.');const info=clean($('.mod.detail .right p').text())??'';const author=clean(/作者[：:]\s*(.+?)(?=类型|字数|人气|$)/u.exec(info)?.[1])??clean($('.mod.detail .author').text());const kind=clean(/类型[：:]\s*(.+?)(?=字数|人气|$)/u.exec(info)?.[1]);const statusText=clean($('.mod.detail .status').text());const status=statusText?.includes('完结')===true?'completed':statusText?.includes('连载')===true?'ongoing':'unknown';const intro=clean($('.mod.book-intro .bd').text());const latest=clean($('.mod.block.update.chapter-list .bd li a').first().text());const coverRaw=$('.mod.detail img,.detail img').first().attr('src');const cover=coverRaw===undefined?null:this.#proxy(new URL(coverRaw,url),url);return Object.freeze({...summary(url,title,author,cover,intro,null,latest,kind===null?[]:[kind]),aliases:Object.freeze([]),catalogUrl:url.toString(),status});}
  async chapters(id:string){const first=decode(id,'book');const items:{id:string;title:string;order:number;url:string;volumeTitle:null;wordCount:null;updatedAt:null;isLocked:false;attributes:readonly never[]}[]=[];const seen=new Set<string>();let url=first;for(let page=0;page<100;page+=1){const html=await this.#cache.getOrFetchText(url,catalogPolicy,()=>this.#browser(url,'GET',null));const $=cheerio.load(html);const blocks=$('.mod.block.update.chapter-list');const block=blocks.length>=2?blocks.eq(1):blocks.eq(0);block.find('.bd li a').each((_,element)=>{const href=$(element).attr('href');const title=clean($(element).text());if(href===undefined||title===null)return;const chapter=new URL(href,url);if(!isChapter(chapter)||seen.has(chapter.toString()))return;seen.add(chapter.toString());items.push({id:`chapter:${token(chapter)}`,title,order:items.length,url:chapter.toString(),volumeTitle:null,wordCount:null,updatedAt:null,isLocked:false,attributes:Object.freeze([])});});const next=$('a.nextPage,.pagelistbox .nextPage').first().attr('href');if(next===undefined)break;const candidate=new URL(next,url);if(candidate.toString()===url.toString()||candidate.origin!==origin)break;url=candidate;}if(items.length===0)throw new Error('Catalog is empty.');return Object.freeze({items:Object.freeze(items)});}
  async content(id:string,chapterId:string){decode(id,'book');let url=decode(chapterId,'chapter');const lines:string[]=[];const seen=new Set<string>();for(let page=0;page<15&&!seen.has(url.toString());page+=1){seen.add(url.toString());const html=await this.#browser(url,'GET',null);const $=cheerio.load(html);const raw=$('#nr1').text();for(const value of raw.split(/\r?\n/u)){const line=value.replace(/[\u00a0\u3000]/gu,' ').trim();if(line!==''&&!/(?:本章未完|点击.*继续阅读|加入书签|章节报错|第一版主)/u.test(line))lines.push(line);}let next:URL|undefined;$('.chapterPages a[href]').each((_,element)=>{if(next!==undefined)return;const candidate=new URL($(element).attr('href')!,url);const number=Number(/_(\d+)\.html$/u.exec(candidate.pathname)?.[1]??candidate.searchParams.get('fenye'));const current=Number(/_(\d+)\.html$/u.exec(url.pathname)?.[1]??url.searchParams.get('fenye')??1);if(number===current+1)next=candidate;});if(next===undefined||next.toString()===url.toString())break;url=next;}const text=lines.join('\n\n');if(text==='')throw new Error('Chapter text is empty.');return Object.freeze({chapterId,contentKind:'novel' as const,title:null,updatedAt:null,text,pages:Object.freeze([])});}
  async resource(request:Record<string,unknown>){if(request.kind!=='image'||typeof request.url!=='string'||typeof request.referer!=='string')return empty(400);const url=new URL(request.url);const referer=new URL(request.referer);if(url.origin!==origin||referer.origin!==origin)return empty(400);const response=await this.context.http.fetch(url,{headers:{accept:'image/*',referer:referer.toString()}});const body=new Uint8Array(await response.arrayBuffer());const type=response.headers.get('content-type');return Object.freeze({status:response.status,headers:type===null?{}:{'content-type':type},body});}
  #browser(url:URL,method:'GET'|'POST',body:string|null){const operation=this.#browserTail.then(()=>this.#browserNow(url,method,body));this.#browserTail=operation.then(()=>undefined,()=>undefined);return operation;}
  async #browserNow(url:URL,method:'GET'|'POST',body:string|null){const page=await this.#page();await this.#ready(page);let response=await this.#fetch(page,url,method,body);if(needsVerification(response.status,response.body)){this.#readyPromise=undefined;await this.#verify(page,method==='GET'?url:new URL(origin));this.#readyPromise=Promise.resolve();response=await this.#fetch(page,url,method,body);}if(response.status>=400)throw new Error(`Browser request failed with status ${response.status}.`);if(typeof response.body!=='string')throw new Error('Browser returned a non-text response.');if(isCf(response.body))throw new Error('Browser verification is incomplete.');return response.body;}
  async #page(){if(this.#pagePromise!==undefined)return this.#pagePromise;const pending=this.context.webview.open({visible:false,timeoutMs:browserTimeoutMs});this.#pagePromise=pending;try{return await pending;}catch(error){if(this.#pagePromise===pending)this.#pagePromise=undefined;throw error;}}
  async #ready(page:WebViewPage){if(this.#readyPromise!==undefined)return this.#readyPromise;const pending=this.#verify(page,new URL(origin));this.#readyPromise=pending;try{await pending;}catch(error){if(this.#readyPromise===pending)this.#readyPromise=undefined;throw error;}}
  async #verify(page:WebViewPage,url:URL){await page.navigate(url.toString(),{timeoutMs:browserTimeoutMs});let html=await page.getHtml({timeoutMs:browserTimeoutMs});if(isCf(html)){await page.show({timeoutMs:browserTimeoutMs});await page.waitForText({text:'第一版主',scope:'text',timeoutMs:browserTimeoutMs});const current=new URL(await page.getUrl({timeoutMs:browserTimeoutMs}));if(current.origin!==origin)throw new Error('Browser verification left the source origin.');html=await page.getHtml({timeoutMs:browserTimeoutMs});if(isCf(html))throw new Error('Browser verification is incomplete.');}await page.hide({timeoutMs:browserTimeoutMs});}
  #fetch(page:WebViewPage,url:URL,method:'GET'|'POST',body:string|null){return page.fetch({url:url.toString(),method,headers:method==='POST'?{'content-type':'application/x-www-form-urlencoded',accept:'text/html'}:{accept:'text/html'},body,responseType:'text',timeoutMs:browserTimeoutMs});}
  #proxy(url:URL,referer:URL){return this.context.resource.proxy({kind:'image',url:url.toString(),referer:referer.toString()});}
}
function summary(url:URL,title:string,author:string|null,coverUrl:string|null,description:string|null,wordCount:number|null,latest:string|null,categories:readonly string[]):Summary{return Object.freeze({id:`book:${token(url)}`,title,contentKind:'novel',author,url:url.toString(),coverUrl,description,language:'zh-CN',status:'unknown',access:'free',wordCount,chapterCount:null,publishedAt:null,updatedAt:null,latestChapter:latest===null?null:{id:null,title:latest,url:null,updatedAt:null},categories:Object.freeze(categories),tags:Object.freeze([]),attributes:Object.freeze([])});}
function token(url:URL){return Buffer.from(`${url.pathname}${url.search}`,'utf8').toString('base64url');} function decode(value:string,prefix:'book'|'chapter'){const match=new RegExp(`^${prefix}:([A-Za-z0-9_-]+)$`,'u').exec(value);if(match?.[1]===undefined)throw new Error('Opaque ID is invalid.');const url=new URL(Buffer.from(match[1],'base64url').toString('utf8'),origin);if(url.origin!==origin||(prefix==='book'?!isBook(url):!isChapter(url)))throw new Error('Opaque ID is invalid.');return url;} function isBook(url:URL){return url.origin===origin&&(/\/list\/\d+(?:_\d+)*\.html$/u.test(url.pathname)||url.pathname==='/wap.php');} function isChapter(url:URL){return url.origin===origin&&(/\/view\/\d+(?:_\d+)?\.html$/u.test(url.pathname)||(url.pathname==='/wap.php'&&url.searchParams.get('action')==='article'));}
function clean(value:string|undefined){const result=value?.replace(/\s+/gu,' ').trim()??'';return result===''?null:result;} function parseCount(value:string){const match=/([0-9]+(?:\.[0-9]+)?)(万?)/u.exec(value);if(match?.[1]===undefined)return null;const count=Math.round(Number(match[1])*(match[2]==='万'?10000:1));return Number.isSafeInteger(count)?count:null;} function isCf(body:string){return /(?:cf-challenge|cf-turnstile|Just a moment|Checking your browser)/iu.test(body);} function needsVerification(status:number,body:unknown){return status===403||status===503||(typeof body==='string'&&isCf(body));} function empty(status:number){return Object.freeze({status,headers:Object.freeze({}),body:new Uint8Array()});}
