/** Plugin API adapter for repository UUID `xiezhenji`. */
import { categories, type Context, XiezhenjiSource } from './source.js';
interface RequestContext extends Context { readonly dataDir: string; readonly app: object; readonly plugin: object; }
interface PageRequest { readonly cursor: string | null; readonly pageSize: number; }
let context: RequestContext | undefined; let source: XiezhenjiSource | undefined;
export async function activate(next: RequestContext) { context = next; next.log.info('source_activated'); }
export async function search(request: PageRequest & { readonly query: string }) { const page = cursor(request.cursor, 'search'); const items = (await requireSource().search(request.query, page)).slice(0, request.pageSize); return Object.freeze({ items, nextCursor: items.length === request.pageSize ? `search:${page + 1}` : null, totalCount: null }); }
export async function discover(request: PageRequest & { readonly target: string | null; readonly collectionId: string | null }) { if (request.target === null) return Object.freeze({ kind: 'document', document: { components: Object.freeze([{ type: 'section', id: 'categories-section', title: '分类', subtitle: null, children: Object.freeze([{ type: 'categoryCollection', id: 'categories', layout: 'grid', categories: Object.freeze(categories.map(([id,title]) => Object.freeze({ id, title, target: `category:${id}`, count: null, url: null }))) }]) }]) } }); const match = /^category:([a-z-]+)$/u.exec(request.target); if (match?.[1] === undefined) throw new Error('Target is invalid.'); const page = cursor(request.cursor, `category:${match[1]}`); const items = (await requireSource().discover(match[1], page)).slice(0, request.pageSize).map((content) => Object.freeze({ content, rank: null, metric: null, recommendation: null })); const collectionId = `category-books:${match[1]}`; const continuation = items.length === request.pageSize ? Object.freeze({ target: request.target, cursor: `category:${match[1]}:${page + 1}` }) : null; if (request.collectionId !== null) return Object.freeze({ kind: 'append', collectionId, items: Object.freeze(items), continuation }); return Object.freeze({ kind: 'document', document: { components: Object.freeze([{ type: 'section', id: `${collectionId}-section`, title: categories.find(([id]) => id === match[1])?.[1] ?? '分类', subtitle: null, children: Object.freeze([{ type: 'contentCollection', id: collectionId, layout: 'coverGrid', items: Object.freeze(items), continuation }]) }]) } }); }
export async function searchSuggestions() { return Object.freeze({ items: Object.freeze([]), nextCursor: null }); } export async function getDetail(request: { readonly id: string }) { return requireSource().detail(request.id); } export async function getChapters(request: { readonly id: string }) { return requireSource().chapters(request.id); } export async function getContent(request: { readonly id: string; readonly chapterId: string }) { return requireSource().content(request.id, request.chapterId); } export async function resource(request: Record<string, unknown>) { return requireSource().resource(request); }
function requireSource() { if (context === undefined) throw new Error('Source is not activated.'); return source ??= new XiezhenjiSource(context); } function cursor(value: string | null, scope: string) { if (value === null) return 1; const match = new RegExp(`^${scope.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&')}:(\\d+)$`, 'u').exec(value); const page = Number(match?.[1]); if (!Number.isSafeInteger(page) || page < 2) throw new Error('Cursor is invalid.'); return page; }
