/**
 * 瓜子体育原生数据源。
 *
 * 职责：独立实现瓜子体育 AES-CBC 请求协议，读取赛程、详情及直播线路。
 * 生命周期：activate 注入 Runtime；不持久化设备或登录状态。
 * IO：加密 API 走 ctx.http；队标与直播媒体经 ctx.resource.proxy。
 * 稳定标识：赛事使用上游 mid，线路使用播放地址摘要。
 */
import { createCipheriv, createDecipheriv, createHash } from 'node:crypto';
import type { MgReadPluginContext } from '@mgread/source-api';
type Json=Record<string,unknown>;type Context=MgReadPluginContext;
const base='https://api.46d5umpk.com',referer='http://WJiZxLXA2.com/',apiHeaders=Object.freeze({'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0 Safari/537.36','Content-Type':'application/json;charset=UTF-8',Accept:'application/json, text/plain, */*'}),playHeaders=Object.freeze({'User-Agent':'Lavf/57.83.100',Referer:referer}),key=Buffer.from('KANGEQIU@8868!~.','utf8'),iv=Buffer.from('0200010900030207','utf8'),categories=Object.freeze([['hot','热门'],['nba','NBA'],['football','足球'],['basketball','篮球']]as const);let context:Context|undefined;
export async function activate(next:Context):Promise<void>{context=next;next.log.info('source_activated');}
export async function search(_request:{query:string;cursor:string|null;pageSize:number}){return frozen({items:[],nextCursor:null,totalCount:0});}
export async function searchSuggestions(_request:{cursor:string|null;pageSize:number}){return frozen({items:[],nextCursor:null});}
export async function discover(request:{target:string|null;cursor:string|null;collectionId:string|null;pageSize:number}){if(request.target===null){if(request.cursor!==null||request.collectionId!==null)throw new Error('Initial discovery request is invalid.');return frozen({kind:'document'as const,document:{components:[{type:'section',id:'guazi-categories',title:'瓜子体育',subtitle:'按赛事类型浏览',icon:'video',children:[{type:'categoryCollection',id:'guazi-category-list',layout:'chips',categories:categories.map(([id,title])=>({id,title,target:`category:${id}`,count:null,url:null,icon:'video'}))}]}]}});}const category=categories.find(([id])=>request.target===`category:${id}`);if(category===undefined)throw new Error('Discovery target is invalid.');if(request.cursor!==null)throw new Error('Discovery cursor is unsupported.');const [id,title]=category,limit=clamp(request.pageSize),rows=await encryptedPost('/gz/live/sports',categoryPayload(id)),values=records(rows).filter(isCurrent).map(matchSummary).filter(notNull).slice(0,limit),collectionId=`guazi:${id}`,items=values.map(content=>frozen({content,rank:null,metric:null,recommendation:null})),continuation=null;if(request.collectionId!==null){if(request.collectionId!==collectionId)throw new Error('Discovery collection is invalid.');return frozen({kind:'append'as const,collectionId,items,continuation});}return frozen({kind:'document'as const,document:{components:[{type:'section',id:`${collectionId}:section`,title,subtitle:null,icon:'video',children:[{type:'contentCollection',id:collectionId,layout:'coverGrid',items,continuation}]}]}});}
export async function getDetail(request:{id:string}){const mid=contentId(request.id),data=object(await encryptedPost('/gz/live/detail',{mid})),item=matchSummary({...data,mid});if(item===null)throw new Error('Match detail is invalid.');return frozen({...item,description:`${item.description??''}\n不要相信视频中的任何广告。`.trim(),aliases:[],catalogUrl:null});}
export async function getChapters(request:{id:string}){const mid=contentId(request.id),data=object(await encryptedPost('/gz/live/detail',{mid})),lines=records(data.live_line),items=lines.map((line,index)=>chapter(mid,line,index)).filter(notNull);return frozen({items,groups:items.length===0?[]:[frozen({id:`group:${encodeKey(mid)}:live`,title:'直播线路',order:0,episodes:items})]});}
export async function getContent(request:{id:string;chapterId:string}){const mid=contentId(request.id),wanted=chapterKey(request.chapterId,mid),data=object(await encryptedPost('/gz/live/detail',{mid})),line=records(data.live_line).find((value,index)=>lineKey(value,index)===wanted),upstream=line===undefined?'':lineUrl(line);if(!safeUrl(upstream))throw new Error('Chapter ID is invalid.');const resourceType=/\.m3u8(?:$|[?#])/iu.test(upstream)?'hls':'video';return frozen({chapterId:request.chapterId,contentKind:'video',title:line===undefined?null:nullable(first(line.name,line.title)),updatedAt:null,text:null,pages:[],media:{url:requireContext().resource.proxy({kind:resourceType,url:upstream,headers:playHeaders}),resourceType,resourcePolicy:'sessionOnly',expiresAt:null,mimeType:resourceType==='hls'?'application/vnd.apple.mpegurl':'video/mp4',headers:playHeaders}});}
async function encryptedPost(path:string,payload:Json):Promise<unknown>{const body=JSON.stringify({parameter:encrypt(JSON.stringify(payload))}),response=await requireContext().http.fetch(`${base}${path}?parameter=key`,{method:'POST',headers:apiHeaders,body});if(!response.ok)throw new Error('Source request failed.');const raw=await response.text();let value:unknown;try{value=JSON.parse(raw);}catch{value=raw;}if(isObject(value)&&value.data!==undefined)value=value.data;if(isObject(value)&&value.data!==undefined)value=value.data;if(typeof value!=='string')return value;const text=value.trim();if(text.startsWith('{')||text.startsWith('['))return JSON.parse(text);const plain=decrypt(text.replaceAll('\\',''));return JSON.parse(plain);}
function encrypt(value:string){const cipher=createCipheriv('aes-128-cbc',key,iv);return Buffer.concat([cipher.update(value,'utf8'),cipher.final()]).toString('base64');}function decrypt(value:string){const decipher=createDecipheriv('aes-128-cbc',key,iv);return Buffer.concat([decipher.update(Buffer.from(value,'base64')),decipher.final()]).toString('utf8');}
function categoryPayload(id:string):Json{if(id==='nba')return{frame:'0',hot:'0',tag:'37',type:'0'};if(id==='football')return{frame:'0',hot:'0',tag:'0',type:'1'};if(id==='basketball')return{frame:'0',hot:'0',tag:'0',type:'2'};return{frame:'0',hot:'1',tag:'0',type:'0'};}
function matchSummary(row:Json){const mid=text(first(row.mid,row.match_id,row.id));if(mid==='')return null;const home=object(row.home),away=object(first(row.visiting,row.away)),homeName=text(home.name),awayName=text(away.name),title=text(row.title)||[homeName,awayName].filter(Boolean).join(' vs ')||mid,event=nullable(first(row.event_name,row.league_name)),start=nullable(first(row.match_time,row.start_time,row.begin_time)),status=nullable(first(row.match_status_info,row.status_text,row.status)),cover=text(first(home.logo,away.logo,row.cover));const id=encodeKey(mid);return frozen({id:`sports:${id}`,title:start===null?title:`[${formatTime(start)}] ${title}`,contentKind:'video',coverOrientation:'landscape',author:event,url:null,coverUrl:proxyImage(cover),description:[start===null?'':`开赛时间：${formatTime(start,true)}`,status===null?'':`状态：${status}`].filter(Boolean).join('\n')||null,language:'zh-CN',status:'unknown',access:'free',wordCount:null,chapterCount:null,publishedAt:null,updatedAt:null,latestChapter:status===null?null:{id:null,title:status,url:null,updatedAt:null},categories:event===null?[]:[event],tags:[],attributes:[]});}
function chapter(mid:string,line:Json,index:number){const url=lineUrl(line);if(!safeUrl(url))return null;return frozen({id:`sports:${encodeKey(mid)}:${lineKey(line,index)}`,title:text(first(line.name,line.title))||`线路${index+1}`,order:index,url:null,volumeTitle:'直播线路',wordCount:null,updatedAt:null,isLocked:null,attributes:[]});}function lineUrl(line:Json){return text(first(line.m3u8,line.url,line.play_url,line.stream_url));}function lineKey(line:Json,index:number){return createHash('sha256').update(lineUrl(line)||String(index)).digest('hex').slice(0,24);}
function isCurrent(row:Json){const value=Number(first(row.m_status,row.match_status));if(Number.isFinite(value)&&value>=2)return false;const time=toMillis(first(row.match_time,row.start_time));return time===0||time>=Date.now()-86400000;}function toMillis(value:unknown){if(typeof value==='number')return value>100000000000?value:value*1000;const raw=text(value);if(/^\d+$/u.test(raw)){const parsed=Number(raw);return parsed>100000000000?parsed:parsed*1000;}const parsed=Date.parse(raw.replaceAll('-','/'));return Number.isFinite(parsed)?parsed:0;}function formatTime(value:unknown,full=false){const ms=toMillis(value);if(ms===0)return text(value);const date=new Date(ms),pad=(number:number)=>String(number).padStart(2,'0'),short=`${pad(date.getMonth()+1)}-${pad(date.getDate())} ${pad(date.getHours())}:${pad(date.getMinutes())}`;return full?`${date.getFullYear()}-${short}`:short;}
function contentId(id:string){const encoded=/^sports:([^:]+)$/u.exec(id)?.[1];if(encoded===undefined)throw new Error('Content ID is invalid.');return decodeKey(encoded);}function chapterKey(id:string,mid:string){const prefix=`sports:${encodeKey(mid)}:`;if(!id.startsWith(prefix)||id.length===prefix.length)throw new Error('Chapter ID is invalid.');return id.slice(prefix.length);}function proxyImage(value:string){if(!safeUrl(value))return null;return requireContext().resource.proxy({kind:'image',url:value,headers:{Referer:referer}});}function safeUrl(value:string){try{const url=new URL(value);return(url.protocol==='https:'||url.protocol==='http:')&&url.username===''&&url.password==='';}catch{return false;}}
function encodeKey(value:string){return Buffer.from(value,'utf8').toString('base64url');}function decodeKey(value:string){if(!/^[A-Za-z0-9_-]+$/u.test(value))throw new Error('Source key is invalid.');return Buffer.from(value,'base64url').toString('utf8');}function first(...values:unknown[]){return values.find(value=>value!==null&&value!==undefined&&value!=='')??'';}function records(value:unknown):Json[]{return Array.isArray(value)?value.filter(isObject):[];}function object(value:unknown):Json{return isObject(value)?value:{};}function isObject(value:unknown):value is Json{return value!==null&&typeof value==='object'&&!Array.isArray(value);}function text(value:unknown){return typeof value==='string'?value.trim():typeof value==='number'?String(value):'';}function nullable(value:unknown){const result=text(value);return result===''?null:result;}function notNull<T>(value:T|null):value is T{return value!==null;}function clamp(value:number){return Math.max(1,Math.min(50,Math.floor(value)));}function frozen<T>(value:T):T{return Object.freeze(value);}function requireContext():Context{if(context===undefined)throw new Error('Source is not activated.');return context;}
