/// 与布局无关的阅读位置和书签公共模型。
///
/// 持久位置始终使用稳定章节、段落与字符锚点。
part of 'models.dart';

@immutable
/// A layout-independent reading position persisted by the host.
class ReaderProgress {
  /// Creates a semantic reading position independent of page or pixel layout.
  const ReaderProgress({
    required this.chapterId,
    required this.paragraphId,
    this.characterOffset = 0,
    this.chapterIndex = 0,
    this.chapterFraction = 0,
    this.bookFraction = 0,
  });

  /// Creates the book information preview position before chapter zero.
  const ReaderProgress.bookPreview()
    : chapterId = '',
      paragraphId = '',
      characterOffset = 0,
      chapterIndex = -1,
      chapterFraction = 0,
      bookFraction = 0;

  /// Stable chapter identifier, or an empty string for the book preview.
  final String chapterId;

  /// Stable paragraph identifier, or an empty string for the book preview.
  final String paragraphId;

  /// UTF-16 character offset within [paragraphId].
  final int characterOffset;

  /// Zero-based chapter order, or `-1` for the book preview.
  final int chapterIndex;

  /// Displayable progress through the current chapter from 0 to 1.
  final double chapterFraction;

  /// Displayable progress through the full book from 0 to 1.
  final double bookFraction;

  /// Whether this position represents the metadata page before chapter zero.
  bool get isBookPreview => chapterIndex < 0;

  /// Returns a copy with the supplied fields replaced.
  ReaderProgress copyWith({
    String? chapterId,
    String? paragraphId,
    int? characterOffset,
    int? chapterIndex,
    double? chapterFraction,
    double? bookFraction,
  }) {
    return ReaderProgress(
      chapterId: chapterId ?? this.chapterId,
      paragraphId: paragraphId ?? this.paragraphId,
      characterOffset: characterOffset ?? this.characterOffset,
      chapterIndex: chapterIndex ?? this.chapterIndex,
      chapterFraction: chapterFraction ?? this.chapterFraction,
      bookFraction: bookFraction ?? this.bookFraction,
    );
  }

  @override
  bool operator ==(Object other) =>
      other is ReaderProgress &&
      chapterId == other.chapterId &&
      paragraphId == other.paragraphId &&
      characterOffset == other.characterOffset &&
      chapterIndex == other.chapterIndex &&
      chapterFraction == other.chapterFraction &&
      bookFraction == other.bookFraction;

  @override
  int get hashCode => Object.hash(
    chapterId,
    paragraphId,
    characterOffset,
    chapterIndex,
    chapterFraction,
    bookFraction,
  );
}

@immutable
/// A host-persisted bookmark anchored to chapter and paragraph identities.
class ReaderBookmark {
  /// Creates a bookmark anchored to a semantic reading position.
  const ReaderBookmark({
    required this.id,
    required this.bookId,
    required this.chapterId,
    required this.paragraphId,
    required this.characterOffset,
    required this.chapterTitle,
    required this.excerpt,
    required this.createdAt,
  });

  /// Stable bookmark identifier generated by the reader.
  final String id;

  /// Stable identifier of the bookmarked book.
  final String bookId;

  /// Stable identifier of the bookmarked chapter.
  final String chapterId;

  /// Stable identifier of the bookmarked paragraph.
  final String paragraphId;

  /// UTF-16 character offset within [paragraphId].
  final int characterOffset;

  /// Chapter title captured for display.
  final String chapterTitle;

  /// Short plain-text excerpt captured for display.
  final String excerpt;

  /// Time at which the reader created the bookmark.
  final DateTime createdAt;
}
