import { categories, type Context, BzSource } from './source.js';

interface Active extends Context { readonly dataDir: string; readonly app: object; readonly plugin: object; }
interface Page { readonly cursor: string | null; readonly pageSize: number; }
let context: Active | undefined;
let source: BzSource | undefined;

export async function activate(next: Active) { context = next; next.log.info('source_activated'); }
export async function search(request: Page & { readonly query: string }) { return invoke('search', async () => { if (request.cursor !== null) throw new Error('Search cursor unsupported.'); const items = (await req().search(request.query)).slice(0, request.pageSize); return Object.freeze({ items, nextCursor: null, totalCount: null }); }); }
export async function discover(request: Page & { readonly target: string | null; readonly collectionId: string | null }) { return invoke('discover', async () => { if (request.target === null) { if (request.cursor !== null || request.collectionId !== null) throw new Error('Initial discovery request is invalid.'); const content = (await req().discover('all', 1)).slice(0, Math.min(request.pageSize, 10)); return categoriesDocument(content); } const match = /^category:([a-z-]+)$/u.exec(request.target); if (match?.[1] === undefined) throw new Error('Target invalid.'); const page = cursor(request.cursor, `category:${match[1]}`); const items = (await req().discover(match[1], page)).slice(0, request.pageSize).map(content => Object.freeze({ content, rank: null, metric: null, recommendation: null })); const collectionId = `category-books:${match[1]}`; const continuation = items.length === request.pageSize ? Object.freeze({ target: request.target, cursor: `category:${match[1]}:${page + 1}` }) : null; if (request.collectionId !== null) return Object.freeze({ kind: 'append', collectionId, items: Object.freeze(items), continuation }); return Object.freeze({ kind: 'document', document: { components: Object.freeze([{ type: 'section', id: `${collectionId}-section`, title: categories.find(([id]) => id === match[1])?.[1] ?? '分类', subtitle: null, children: Object.freeze([{ type: 'contentCollection', id: collectionId, layout: 'list', items: Object.freeze(items), continuation }]) }]) } }); }); }
export async function searchSuggestions() { return Object.freeze({ items: Object.freeze([]), nextCursor: null }); }
export async function getDetail(request: { readonly id: string }) { return invoke('detail', () => req().getDetail(request.id)); }
export async function getChapters(request: { readonly id: string }) { return invoke('chapters', () => req().chapters(request.id)); }
export async function getContent(request: { readonly id: string; readonly chapterId: string }) { return invoke('content', () => req().content(request.id, request.chapterId)); }

function req() { if (context === undefined) throw new Error('Source not activated.'); return source ??= new BzSource(context); }
function categoriesDocument(content: readonly Awaited<ReturnType<BzSource['discover']>>[number][]) { const items = Object.freeze(content.map(value => Object.freeze({ content: value, rank: null, metric: null, recommendation: null }))); return Object.freeze({ kind: 'document', document: { components: Object.freeze([...(items.length === 0 ? [] : [{ type: 'section', id: 'latest-section', title: '最近更新', subtitle: '全站新近更新作品', icon: 'ongoing', children: Object.freeze([{ type: 'contentCollection', id: 'latest-books', layout: 'shelf', items, continuation: null }]) }]), { type: 'section', id: 'categories-section', title: '小说分类', subtitle: '按榜单或题材继续发现', icon: 'explore', children: Object.freeze([{ type: 'categoryCollection', id: 'categories', layout: 'chips', categories: Object.freeze(categories.map(([id, title]) => Object.freeze({ id, title, target: `category:${id}`, count: null, url: null, icon: id === 'all' ? 'books' : id === 'fantasy' ? 'fantasy' : id === 'martial' ? 'wuxia' : id === 'city' ? 'urban' : id === 'history' ? 'history' : id === 'scifi' ? 'scienceFiction' : 'category' }))) }]) }]) } }); }
async function invoke<T>(name: string, action: () => Promise<T>) { if (context === undefined) throw new Error('Source not activated.'); context.log.info(`source_${name}_started`); try { const result = await action(); context.log.info(`source_${name}_completed`); return result; } catch (error) { const code = error instanceof Error && error.message === 'Browser verification is incomplete.' ? 'browser_verification_incomplete' : error instanceof Error ? error.name : typeof error; context.log.warn(`source_${name}_failed error_code=${code}`); throw error; } }
function cursor(value: string | null, scope: string) { if (value === null) return 1; const page = Number(new RegExp(`^${scope}:(\\d+)$`, 'u').exec(value)?.[1]); if (!Number.isSafeInteger(page) || page < 2) throw new Error('Cursor invalid.'); return page; }
