import assert from'node:assert/strict';import test from'node:test';import*as plugin from'../dist/index.mjs';test('275 native HTML flow parses catalog and proxies audio',async()=>{const resources=[],list='<div class="grid"><a href="/book/39328.html"><img src="/cover.jpg" alt="凡人修仙传"><h3>凡人修仙传</h3><p class="line-clamp-2">简介</p></a></div>',detail='<h1 class="text-2xl">凡人修仙传</h1><div class="line-clamp-3">详细简介</div><a id="chapter-pos-1" href="/play/39328/23406840.html"><span class="text-sm text-gray-700">第一集</span></a>',play='<script>const player={url:"https://media.example/one.m4a"};</script>';await plugin.activate({log:{info(){},warn(){}},resource:{proxy(v){resources.push(v);return`http://127.0.0.1/resource/${resources.length}`;}},http:{async fetch(input){const url=String(input);return new Response(url.includes('/play/')?play:url.includes('/book/')?detail:list);}}});const root=await plugin.discover({target:null,cursor:null,collectionId:null,pageSize:5});const id=root.document.components[0].children[0].items[0].content.id;assert.equal(id,'audio:39328');const found=await plugin.search({query:'凡人',cursor:null,pageSize:5});assert.equal(found.items[0].title,'凡人修仙传');const info=await plugin.getDetail({id});assert.equal(info.description,'详细简介');const chapters=await plugin.getChapters({id});const content=await plugin.getContent({id,chapterId:chapters.items[0].id});assert.equal(content.media.resourceType,'audio');assert.equal(resources.find(v=>v.kind==='audio').url,'https://media.example/one.m4a');});

function discoveryCollections(result) {const found=[]; const visit=node=>{if(node.type==='contentCollection')found.push(node);for(const child of node.children??[])visit(child);};for(const node of result.document?.components??[])visit(node);return found;}
test('homepage continuation retains every book without inventing routes',async()=>{
 const html=Array.from({length:13},(_,i)=>'<a href="/book/'+(100+i)+'.html"><h3>Book '+i+'</h3></a>').join('');
 await plugin.activate({log:{info(){}},resource:{proxy:v=>v.url},http:{fetch:async()=>new Response(html)}});
 const root=await plugin.discover({target:null,cursor:null,collectionId:null,pageSize:50});const list=discoveryCollections(root)[0];
 assert.equal(list.items.length,10);const tail=await plugin.discover({...list.continuation,collectionId:list.id,pageSize:50});
 assert.equal(tail.items.length,3);assert.equal(tail.continuation,null);assert.equal(new Set([...list.items,...tail.items].map(x=>x.content.id)).size,13);
 await assert.rejects(plugin.discover({target:'home',cursor:'other:1',collectionId:list.id,pageSize:3}));
 await assert.rejects(plugin.discover({target:null,cursor:'home:1',collectionId:null,pageSize:3}));
});